### ISSUE TITLE
hs-blastn without windowmasker

### ISSUE THREAD

**Issue by snayfach** [chenying2016/queries#2]
Would it be possible to run hs-blastn without windowmasker? I'd like to use hs-blastn but I don't want to mask any reference sequences. I'm considering incorporating your tool into a new open source pipeline.

Thanks,
Stephen

**Comment by chenying2016** [comment]
Dear Stephen:
    HS-BLASTN is currently not suitable for repeat-region-rich references such as the human genome. So that the repeat regions must be masked out before searching against the database. If your target reference contains no or few repeat regions, HS-BLASTN will also work well even if the windowmasker is used. Because in that case no subsequence will be masked out by the windowmasker. If you have any further ideas or suggestions, please don't hesitate to tell me. Thanks!

Ying Chen

**Comment by snayfach** [comment]
My reference database consists of universal-single-copy genes from bacteria. I am using this reference database to determine what species of bacteria are present in a shotgun metagenome. Because these sequences can be quite similar, it appears that windowmasker is making out some reference sequences. When compared to blastn without windowmasker, hs-blastn returns 25% fewer query sequences from a test that I ran.

**Comment by chenying2016** [comment]
In next week we will release a new version of hs-blastn, which can run without a windowmasker.

**Comment by snayfach** [comment]
Thank you. I look forward to the new release.

**Comment by snayfach** [comment]
I know it's only been a week, but is there any update on this?

**Comment by chenying2016** [comment]
The new version hs-blastn-0.0.4+ has been uploaded.

**Comment by snayfach** [comment]
I can confirm that hs-blastn now produces the same results as blastn when run without windowmasker. Thanks!!
