### ISSUE TITLE
libgomp: Thread creation failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by lisboazootec** [chenying2016/queries#22]
Alignment being interrupted with the following error message "libgomp: Thread creation failed: Resource temporarily unavailable". What is going on?

**Comment by chenying2016** [comment]
It seems that the number of running threads on your system exceeds the system limit. To see the number of maximal allowed running threads or processes, you can run the command
```shell
ulimit -u
```
and see the output. On the other hand, to see how many threads or processes have been created by the system, you can run the command
```
ps -eLF | wc -l
```
and see the output. If the later is close  or equal to the former, then the problem you are facing is likely to occur.
