### ISSUE TITLE
Question about comparing with results, speed and memory consumption of current megablast

### ISSUE THREAD

**Issue by josruirod** [chenying2016/queries#29]
Hi and thanks for your interesting tool.

I would like to use it on a pipeline for automatic correction of genome assemblies, that currently struggles with an implementation of gnu's parallel and blastn/megablast, because it's slow and with huge memory consumption for large sequences. I think your tool would be key. 

I'm aware that the current version no longer provides the same results than megablast/blastn, but can this still be achieved? For now and for the sake of compatibility, I would need to obtain the same results. Also, any comment you could have on whether the amount of RAM required for your tool to run successfully can be predicted or controlled somehow. I read about the option r in the publication, but I'm unsure it it still applies.

Thanks for your time and any insight

**Comment by chenying2016** [comment]
If you need the same results as ncbi-blastn (megablast), please use the original version. https://github.com/chenying2016/queries/tree/master/hs-blastn-src/v0.0.5. Also, if your database (usually in FASTA format) is very large, please split the database into small chunks (each chunk of 8 Gbp is suggested). And search your queries on each chunk.

**Comment by josruirod** [comment]
Thanks for your kind support. I'm trying to get in a more efficient way the same results than:

> formatdb -p F -i sequence.fa
> megablast -W 40 -F F -a 2 -m 8 -e 1e-80 -d sequence.fa -i query.fa -o out.blast

So far, I've installed v0.0.5 and tested:

> makeblastdb -in sequence.fa -input_type fasta -dbtype nucl
> windowmasker -in sequence.fa -infmt blastdb -mk_counts -out sequence.fa.counts
> windowmasker -in sequence.fa.counts -sformat obinary -out sequence.fa.counts.obinary -convert
> hs-blastn index sequence.fa
> hs-blastn align -db sequence.fa -window_masker_db sequence.fa.counts.obinary -query query.fa -out out.blast -outfmt 6 -num_threads 10 -word_size 40 -evalue 1e-80

I'm failing to obtain the same results. Also adding the paramter -dust to try and include the -F F of megablast. Any insight would be much appreciated, thanks

**Comment by chenying2016** [comment]
The inconsistent alignment results are likely caused by two reasons. First, you a using a newer version of blast. As you known, the blast program itself is continuously updated. Another reason is that the blast searching procedure is very complicated and mass. So it is natural that the two aligners output different results. However, the differences should be minor if you using the old version of this program.

**Comment by josruirod** [comment]
I see, and you are right, with previous versions of megablast the results are indeed more similar.
Thank you so much for your help and support
