### ISSUE TITLE
Error when reading from /dev/stdin

### ISSUE THREAD

**Issue by snayfach** [chenying2016/queries#3]
Would it be possible to provide support for streaming query sequences from /dev/stdin? I've tried doing this, but hs-blastn throws an error and does not report all alignments. The output file was missing 11,273  records (out of 145,389) compared to when I ran the program without streaming from /dev/stdin

I ran hs-blastn using the following command:
cat $QUERY | hs-blastn align -query /dev/stdin -db $DB -out $OUT -outfmt 6

And got the following error:
[StreamLineReader] Error: while reading file /dev/stdin unexpected end of file.

**Comment by snayfach** [comment]
Have you been able to reproduce this issue? I'd really appreciate it if it could be addressed. Thank you

**Comment by chenying2016** [comment]
Thanks for your suggestion! I am working on it, which will approximately takes one week. And I will inform you when it is done.

**Comment by chenying2016** [comment]
Dear snayfach, I have fixed the two bugs you raised up. Please download the new source codes. Thanks again for your suggestions for improving the quality of HS-BLASTN. And please let me know  if you have any further ideas.

**Comment by snayfach** [comment]
This is fixed now. Thank you
