### ISSUE TITLE
Error when using -perc_identity

### ISSUE THREAD

**Issue by enormandeau** [chenying2016/queries#5]
When using the -perc_identity with a number between 0 and 100, I get the following error:

Fatal Error: Unrecognized arguments: -out

(using Linux Mint 17)

**Comment by chenying2016** [comment]
Thanks for your suggestion! HS-BLASTN currently does not support this option. And I am now trying to adding it to HS-BLASTN. I will inform you (in about one week) when I finish it.

**Comment by chenying2016** [comment]
Dear enormandeau, thanks for your suggestion again! Now I have fixed this bug and HS-BLASTN supports this options successfully. Please download the new source codes. If you have any further suggestions, please tell me, thank you!
