### ISSUE TITLE
hs-blastn syntax error

### ISSUE THREAD

**Issue by toth-greg-2016** [chenying2016/queries#7]
When I run hs-blastn align with the tested queries and hg38.fa:
./hs-blastn align -db hg38.fa -window_masker_db ./hg38.fa.counts.obinary -query ./HSQueriesSmall.fa -out results_HSQueriesSmall.fa -outfmt 6

I get the following output:
[HS-BLASTN] Loading database.
        Loading hg38.fa.sequence, size = 3GB
        Loading hg38.fa.bwt, size = 3GB
        Loading hg38.fa.sa, size = 6GB
[CSeqMaskerIstatAscii, 37835l] syntax error.
Aborted (core dumped)

The corresponding megablast run is fine:
./blastn -task megablast -db ./hg38.fa -window_masker_db ./hg38.fa.counts.obinary -query ./HSQueriesSmall.fa -out ./megablast_results_small.txt -outfmt 6

**Comment by chenying2016** [comment]
The problem has been resolved. Please download the new version of HS-BLASTN.

**Comment by toth-greg-2016** [comment]
Ying Chen,

The program has continued to work well for us – thanks!

Could you provide the default settings for hs-blastn?

Greg

**Comment by chenying2016** [comment]
The default values for the complete options can be found in the file
queries/hs-blastn-src/commandline_options/options.cpp.

2016-04-15 4:48 GMT+08:00 toth-greg-2016 notifications@github.com:

**Comment by toth-greg-2016** [comment]
Great - thanks!

Sent from my Windows Phone
