### ISSUE TITLE
makeblastdb Error

### ISSUE THREAD

**Issue by NakanishiTetsuhiro** [chenying2016/queries#9]
I tried makeblastdb in 2. build a blastdb

  makeblastdb -in hg38.fa -input-type fasta -dbtype nucl

As a result, Obtained two errors

  Error: Unknown argument: "input-type"
  Error:  (CArgException::eInvalidArg) Unknown argument: "input-type"

I tried rewrite "input-type" to "input_type"

As a result, Success!

**Comment by chenying2016** [comment]
I have corrected the typos. Thanks for reminding!
